services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=secret
      - DB_NAME=vacation_db
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - FERIADOS_API_KEY=${FERIADOS_API_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: vacation_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - db

volumes:
  db_data:
